### ISSUE TITLE
Exception: java.lang.ClassCastException: class org.vlang.lang.psi.impl.VlangEmbeddedDefinitionImpl cannot be cast to class org.vlang.lang.psi.VlangInterfaceDeclaration (org.vlang.lang.psi.impl.VlangEmbeddedDefinitionImpl and org.vlang.lang.psi.VlangInterfaceDeclaration 

### ISSUE THREAD

**Issue by i582** [intellij-v/intellij-v#412]
### Describe the bug

```
I want to report an IDE Error showed by my IDE:

java.lang.ClassCastException: class org.vlang.lang.psi.impl.VlangEmbeddedDefinitionImpl cannot be cast to class org.vlang.lang.psi.VlangInterfaceDeclaration (org.vlang.lang.psi.impl.VlangEmbeddedDefinitionImpl and org.vlang.lang.psi.VlangInterfaceDeclaration are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @3021bb0d)
	at org.vlang.lang.search.VlangInheritorsLineMarkerProvider.collectSlowLineMarkers(VlangInheritorsLineMarkerProvider.kt:36)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:224)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:104)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:95)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:99)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:379)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1111)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:371)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:370)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:346)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:173)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:344)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

Eeventual the makers Ã³f vlang-intelij can use this to optimize/fix something. Just as quick error report.
```

### Expected Behavior

.

### Current Behavior

.

### Reproduction Steps

.

### Environment details (`v doctor` output)

.

### IDE Type (IDEA Community/Ultimate, GoLand, CLion, etc.)

.

**Comment by i582** [comment]
Already fixed
